### PR TITLE
Host Lookup Abstract & Example

### PR DESCRIPTION
**Pull request by jlost**
Introduces the concept of abstract modules, using Host Lookup as an example. Uses `typings` and a `dataclass` to formalize the types expected by the included templates.

### CODE REVIEW

**Comment by ksofa2** [comment]
@jlost I'm trying to run this, but getting errors. Not sure what I'm doing wrong. In your env, how are you adding to `NETDASH_MODULES`?

**Comment by jlost** [comment]
I pushed a couple changes that I had in the works. It should run if you do a `docker compose up --build`.

In my env, I'm using a simplified `docker-compose`:
```
---
version: '3'

services:

  app:
    build: .
    depends_on:
      - database
    env_file: .env
    ports:
      - 8888:8000
    volumes:
      - .:/usr/src/app
    entrypoint: ../../docker-entrypoint-dev.sh
    command: "python manage.py runserver 0.0.0.0:8000"

  database:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_USER=netdash
      - POSTGRES_DB=netdash
    volumes:
      - netdash-postgres-data:/var/lib/postgresql/data

volumes:
  netdash-postgres-data:
```

And my `.env` is along the lines of:
```
DATABASE_URL=postgres://netdash@database/netdash
NETDASH_SECRET_KEY=12345
NETDASH_DEBUG=True
NETDASH_MODULES=example_hostlookup_dummy,example_devices_dummy,
DJANGO_SETTINGS_MODULE=netdash.settings_env
```

**Comment by jlost** [comment]
I ended up doing some things in this PR that went beyond the scope I expected. 

For one, I swapped out `django-rest-swagger`(which is apparently deprecated despite being featured in DRF's tutorials) for `drf-yasg`, which gives a familiar new option for Swagger UI. But the real reason I did this was in pursuit of generating Swagger definitions for query string parameters. I still had to manually define them with annotations, which rubs me the wrong way (should be able to infer these things from method parameters), but it is what it is. 

Something I wanted to do was drive the interface for the view result and the interface for the body of the API call (i.e. the serializer) off of the same dataclass. At it turns out, there isn't anything out there to do that yet, even though it is possible and would be very useful. I found [this issue](https://github.com/encode/django-rest-framework/issues/6021) where it is discussed. I could probably hack together something that would work for this instance without too much trouble, but making something general-purpose would be a lot more work (would need many unit tests). So I dropped that idea and manually duplicated the dataclass as a Serializer.

**Comment by ksofa2** [comment]
@jlost FYI: I had to run `pipenv lock` to get the --build to work.

**Comment by jlost** [comment]
Thanks, I fixed it.

**Pull request merged**
