### PR TITLE
OAuth for API Use

### PR DESCRIPTION
**Pull request by jlost**
This adds django-oauth-toolkit to support applications calling API views with tokens.

### CODE REVIEW

**Comment by jlost** [comment]
* NetDash Modules need to be able to generate their own Scopes (preferably, repurpose Permissions in some way so there is parity between UI and API permissions).
* Users should only be able to add Scopes to their Application if they have access to that Scope (this can be facilitated by some relationship between permissions & scopes).
* Existing APIs and the NetDash Module template should be modified to fit in with any changes to conventions necessitated by the addition of scopes.

Other, possibly optional tasks:
* Django OAuth Toolkit has no dependency on DRF, so its endpoints don't have any OpenAPI schema metadata. Adding this metadata and making it show up in Swagger would be an improvement in discoverability.
* Provide some way to access & discover the built-in views to add/list/modify Applications

**Comment by jlost** [comment]
Some notes on scopes--

django-auth-toolkit offers scopes as a setting:

```
'SCOPES': {'hostlookup_combined': 'Lookup hosts via the combined module' }
```

You can set permissions of your APIViews using TokenHasScope:

```
class HostLookupCombinedView(views.APIView):
    authentication_classes = [OAuth2Authentication]
    permission_classes = [TokenHasScope]
    required_scopes = ['hostlookup_combined']
```

When requesting an access token, you must specify which scopes you want like so:

`curl -X POST -d "grant_type=password&username=USERNAME&password=PASSWORD&scope=hostlookup_combined bluecat_access_lookup" -u”APPLICATION_ID:SECRET_KEY" BASE_URL/o/token/`

Currently NetDash uses only permissions and not scopes. Scopes could be generated from all permissions available in NetDash.

There are custom scopes backends:
>"Class-based scopes backends. Listing scopes, available scopes and default scopes is now done through the class that the SCOPES_BACKEND_CLASS setting points to. By default, this is set to oauth2_provider.scopes.SettingsScopes which implements the legacy settings-based scope behaviour. No changes are necessary."

We could implement our own Scopes Backend that proxies permissions.

**Comment by jlost** [comment]
The initial use case I'm looking to support is two-legged oauth (client credentials), so I will narrow down on that use case for this PR and tackle three-legged oauth separately down the road.

**Comment by jlost** [comment]
@ksofa2 @rbharadwaj9 
Documentation TBD. Some implementation notes: 
* Uses the `django_oauth_toolkit` app to provide `/api/o/token/` and `/api/o/revoke_token/`.
* I created a 1:1 mapping between OAuth2 scopes and Django permissions to streamline the use of scopes. This could be overridden in a deployment by changing the `SCOPES_BACKEND_CLASS` setting.
* I am only targeting two-legged OAuth2 (client credentials grant type) for this unit of work. I would be happy to accept PRs with tested and working three-legged OAuth. It would probably take little work to get it there.
* `django_oauth_toolkit` is enabled by default. If a particular NetDash deployment has no use for OAuth, it's easy enough to ignore and not use it.
* The current expectation is that admins would create users' OAuth2 Applications through the Admin interface. `django_oauth_toolkit`'s included Application and Token UI views haven't been implemented. I could see these being implemented in a NetDash Module, where they could be optionally enabled.

**Comment by ksofa2** [comment]
Would it make sense to provide `HasScopeOrPermission` somewhere in the `netdash` package? It's good that it's part of the netdash_module_template, but I wonder if that duplication could be problematic later. Or is the module going to need to modify that in a way that inheriting and override stuff isn't conducive to?

**Comment by jlost** [comment]
I did consider that. The duplication isn't ideal. But putting it in the NetDash package and referencing it from modules has its own set of disadvantages:
* Tightly couples NetDash Modules to NetDash core. For example, let's say there is a Django App created outside of ND that I am refactoring to use in ND. By adding an `from netdash.permissions import HasScopeOrPermission`, that Django App can now no longer be used outside of ND. Whereas if I copied it in, I have only added a dependency on `oauth2_provider`.
* Future changes to HasScopeOrPermission could potentially break modules

OTOH... I'm currently demonstrating NetDash Modules inheriting from each other in a way that introduces some tight coupling & fragility (e.g. HostLookup Combined). And it could be that being able to pick up your NetDash Module and use it somewhere else would, in reality, rarely be capitalized on.

**Comment by ksofa2** [comment]
I think you're right that using modules elsewhere will be rare. In cases where that does happen, I'd be fine expecting a higher level of comfort from that developer to manage those problems: they could import the netdash dependancies, or do the duplication of HasScopeOrPermission on their own.

**Comment by jlost** [comment]
@ksofa2 I went ahead & refactored `HasScopeOrPermission` to be part of `netdash_api` (`_api` because it's DRF-dependent). I also added tests specifically for `HasScopeOrPermission`. Could you give it a quick sanity check whenever you get a chance?

**Pull request merged**
